### PR TITLE
Merge pull request #1 from EE590-Winter2015/master

### PR DESCRIPTION
**Pull request by craigboy**
Update slides/ example code from class

### CODE REVIEW

**Comment by staticfloat** [comment]
Hey there.  So you've submitted a Pull Request to my repository, which means you want me to merge changes from your repository into mine, but I don't think that's what you meant to do, since the "Files Changed" tab up above seems to show that no files have actually been changed in your repository relative to mine.  What were you trying to do here?

**Comment by craigboy** [comment]
I was trying to pull the new Week 2 material to my forked repo..... I seemed to have figured this out last time, but has eluded me now.

**Comment by staticfloat** [comment]
You can't do that from the web interface, or from the VS git GUI.  I talked about it in class, today, check out slide 42 in Week 2 about adding another remote to your local repository, and pulling down changes from the other remote (`upstream` in the slides) into your local repository.  Once you've done that, you can push your local changes up to your fork.

**Comment by craigboy** [comment]
Sounds good. I do remember this from class. I seem to remember updating using the web interface last week actually, after you added the youtube video....

**Comment by staticfloat** [comment]
Actually, it looks like you can do this from the web interface, funnily enough.  You need to swap the order of your fork vs. my fork in the pull request interface.  See this [SO answer](http://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface).  There are some comments about how this does weird things to the github web interface and that command-line is better, but that's probably how you did it in the first place.

**Comment by staticfloat** [comment]
You can see that you did in fact do that by looking at the network view, where you very obviously [pulled some of my changes into your fork](https://github.com/EE590-Winter2015/Materials/network).

**Comment by craigboy** [comment]
I see. Interestingly enough, I achieved this result by following github's introduction tutorials. 

I think I will keep to the command line syncing. No need to clutter the graphical interface for other users. Thanks for your help.

**Pull request closed without merging**
